

spring.application.name=phone-shop

# === Database ===
spring.datasource.url=jdbc:postgresql://localhost:5432/phoneshop1
spring.datasource.username=postgres
spring.datasource.password=1234
#spring.datasource.url=jdbc:postgresql://postgres-db:5432/phoneshop_service
#spring.datasource.username=phoneshop_service
#spring.datasource.password=phoneshop#123

spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === JWT ===
app.jwt.secret=phoneshop-super-secret-key-must-be-at-least-256-bits-long-for-hs256
app.jwt.expiration-ms=86400000

# === Server ===
server.port=8080

# === Logging ===
logging.level.com.phoneshop=DEBUG
logging.level.org.springframework.security=INFO

# === Swagger ===
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=10MB
